#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=spiking-initializer-shim \
-p 4000:4000 \
-v "$(pwd)":/app \
-v "$(pwd)"/../spiking-model-configuration/configuration/:/configuration \
louisross/spiking-initializer-shim:1.0 \
bash
